export { default as WhySalesStories } from "./Stories that Speed Sales/1.WhySalesStoriesAreImportant.png";
export { default as SelectingTheRight } from "./Stories that Speed Sales/2.SelectingTheRightStory.png";
export { default as The10Commandments } from "./Stories that Speed Sales/3.The10CommandmentsOfGreatStories.png";
export { default as The5Emotions } from "./Stories that Speed Sales/4.TheFiveEmotionsThatDriveGreatStory.png";
export { default as ElevatorPitch } from "./Stories that Speed Sales/5.ElevatorPitchStory.png";
export { default as EpicCaptureStory } from "./Stories that Speed Sales/6.EPICCaptureStory.png";
export { default as OpeningAStory } from "./Stories that Speed Sales/7.OpeningAStoryWithSCIPAB.png";
export { default as UnicornSales } from "./Stories that Speed Sales/8.UnicornSalesStory.png";
export { default as Wiifm } from "./Stories that Speed Sales/9.WIIFMDemoStory.png";
export { default as TheCloser } from "./Stories that Speed Sales/10.TheCloserStory.png";
export { default as RetainAndGrow } from "./Stories that Speed Sales/11.RetainAndGrowTogetherStories.png";
export { default as NextSteps } from "./Stories that Speed Sales/12.NextSteps.png";
//LIGHTS CAMERA ,ETC
export { default as CourseOverview } from "./Lights, Camera, Sales/0.LightsCameraSales.png";
export { default as WhyStoryWorks } from "./Lights, Camera, Sales/1.WhyStoryMatters.png";
export { default as TheQuest } from "./Lights, Camera, Sales/2.TheQuest.png";
export { default as CustomerJourney } from "./Lights, Camera, Sales/3.CustomerJourney.png";
export { default as The10Lights } from "./Lights, Camera, Sales/4.The10CommandmentsofStory.png";
export { default as TheStuff } from "./Lights, Camera, Sales/5.TheSTUFF.png";
export { default as TheCreativeBrief } from "./Lights, Camera, Sales/6.TheCreativeBrief.png";
export { default as TheIdeaFactory } from "./Lights, Camera, Sales/7.TheIdeaFactory.png";
export { default as ScriptTemplates } from "./Lights, Camera, Sales/8.ScriptTemplates.png";
export { default as TheArtOfPostProduction } from "./Lights, Camera, Sales/9.TheArtofPostProduction.png";
export { default as PostProductionSecrets } from "./Lights, Camera, Sales/10.PostProductionSecrets.png";
//DEMO AND SELL:SHORTCUTS
export { default as Intro } from "./Demo and Sell_ Shortcut to the Finals/1.Intro.png";
export { default as WhatNotToDo } from "./Demo and Sell_ Shortcut to the Finals/2.WhatNotToDo.png";
export { default as Breakdown } from "./Demo and Sell_ Shortcut to the Finals/3.Breakdown.png";
export { default as DiscoverThePain } from "./Demo and Sell_ Shortcut to the Finals/4.DiscoverThePain.png";
export { default as Empathy } from "./Demo and Sell_ Shortcut to the Finals/5.Empathy.png";
export { default as MountainTop } from "./Demo and Sell_ Shortcut to the Finals/6.MountainTop.png";
export { default as OnTeam } from "./Demo and Sell_ Shortcut to the Finals/7.OnTeam.png";
export { default as Story } from "./Demo and Sell_ Shortcut to the Finals/8.Story.png";
export { default as MicroStories } from "./Demo and Sell_ Shortcut to the Finals/9.MicroStories.png";
export { default as ExecDec } from "./Demo and Sell_ Shortcut to the Finals/10.ExecDec.png";
export { default as Listen } from "./Demo and Sell_ Shortcut to the Finals/11.Listen.png";
export { default as LeverageBenefits } from "./Demo and Sell_ Shortcut to the Finals/12.LeverageBenefits.png";
export { default as NextStepsDemo } from "./Demo and Sell_ Shortcut to the Finals/13.NextSteps.png";
//DELIVERING A GREAT VIRTUAL
export { default as WhatMakesAGreatSpeech } from "./Delivering a Great Virtual Sales Pitch/1.WhatMakesAGreatSalesPitch.png";
export { default as TheElementsOfA } from "./Delivering a Great Virtual Sales Pitch/2.TheElementsOfAGreatSalesPitch.png";
export { default as EngageAndEstablish } from "./Delivering a Great Virtual Sales Pitch/3.EngageAndEstablishToGain.png";
export { default as IdentifyYourProspect } from "./Delivering a Great Virtual Sales Pitch/4.IdentifyYourProspectsPainPoints.png";
export { default as CreateImpactInYour } from "./Delivering a Great Virtual Sales Pitch/5.CreateImpactInYourSalesPitch.png";
export { default as AimHigherThan } from "./Delivering a Great Virtual Sales Pitch/6.AimHigherThanClosingTheDeal.png";
export { default as UpgradeYourPitch } from "./Delivering a Great Virtual Sales Pitch/7.UpgradeYourPitchWith5KeyEmotions.png";
export { default as LeverageDifferent } from "./Delivering a Great Virtual Sales Pitch/8.LeverageDifferentLearningStyles.png";
export { default as SpiceUpYourPitch } from "./Delivering a Great Virtual Sales Pitch/9.SpiceUpYourPitch.png";
export { default as TurnObstacleInto } from "./Delivering a Great Virtual Sales Pitch/10.TurnObstaclesIntoOpportunities.png";
export { default as ContinueTransforming } from "./Delivering a Great Virtual Sales Pitch/11.ContinueTransformingYourGreatPitch.png";
//Building Rapport on Virtual Sales Calls
export { default as WhyIsBuildingRapportCriticalTo } from "./Building Rapport on Virtual Sales Calls/1.WhyIsBuildingRapportCritical.png";
export { default as LoseYourAgenda } from "./Building Rapport on Virtual Sales Calls/2.LoseYourAgenda.png";
export { default as ShutDownTheDistractions } from "./Building Rapport on Virtual Sales Calls/3.ShutDownTheDistractions.png";
export { default as ControlTheRoom } from "./Building Rapport on Virtual Sales Calls/4.ControlTheRoom.png";
export { default as WintThePerson } from "./Building Rapport on Virtual Sales Calls/5.WinThePersonNotTheSale.png";
export { default as BuildRapportByBeingReal } from "./Building Rapport on Virtual Sales Calls/6.BuildingRapportByBeingReal.png";
export { default as RelaxMirrorAnd } from "./Building Rapport on Virtual Sales Calls/7.RelaxMirrorAndReiterate.png";
export { default as AskRelatableQuestions } from "./Building Rapport on Virtual Sales Calls/8.AskRelatableQuestions.png";
export { default as LearnToLove } from "./Building Rapport on Virtual Sales Calls/9.LoveToQuestionTheirAnswers.png";
export { default as WhatToAvoid } from "./Building Rapport on Virtual Sales Calls/10.WhatToAvoid.png";
export { default as RapportBuildingIs } from "./Building Rapport on Virtual Sales Calls/11.RapportBuildingisaLearnedTrait.png";
