export const servicesData = [
  {
    id: 1,
    icon: "IconAudioLines",
    title: "Text to Voice",
    description: "Convert your text to voice",
    link: "/texttovoice",
  },
  {
    id: 2,
    icon: "IconLibraryBig",
    title: "Voice Library",
    description: "New Voice Overs Weekly",
    link: "/library",
  },
  {
    id: 3,
    icon: "IconClone",
    title: "Voice Cloning",
    description: "Create any voice you want",
    link: "/voicecloning",
  },
  {
    id: 4,
    icon: "IconEar",
    title: "Translate Audio",
    description: "Audio Files Translations",
    link: "/translateaudio",
  },
  {
    id: 5,
    icon: "IconBrainCog",
    title: "Script Coach",
    description: "Refine your ideas our AI.",
    link: "/chat",
  },
  {
    id: 6,
    icon: "IconGlobe",
    title: "Text Translation",
    description: "Multilingual translation",
    link: "/translatetext",
  },
  {
    id: 7,
    icon: "IconCopyright",
    title: "Plagiarism",
    description: "Online plagiarism detection",
    link: "/plagiarism-detector",
  },
  {
    id: 8,
    icon: "IconNoAi",
    title: "Ai Detector",
    description: "Detect AI-Generated content",
    link: "/ai-detector",
  },
  {
    id: 9,
    icon: "IconGraduationCap",
    title: "Classes",
    description: "Personalized masterclasses",
    link: "/masterclasses",
  },
  {
    id: 10,
    icon: "IconFileHeart",
    title: "Blog",
    description: "Keep up with our latest news",
    link: "https://script-timer.com/blogs/",
  },
  {
    id: 11,
    icon: "FileImageIcon",
    title: "Image Creator",
    description: "Storyboards and Images",
    link: "/image-generator",
  },
  {
    id: 12,
    icon: "IconBookPlus",
    title: "Much More",
    description: "New features soon",
    link: "/",
  },
];
